------------------------------------------------------------------------------
-- Globally Muted Players

-- This is used to mute players VGS and chat seperately.
-- Syntax: mutePlayer(mplayer_custom(PlayerName, MuteVGS, MuteChat, MutePM))
------------------------------------------------------------------------------
--mutePlayer(mplayer_custom("Exampleplayer1", true, true, false))
--mutePlayer(mplayer_custom("Exampleplayer2", true, false, false))
--mutePlayer(mplayer_custom("Exampleplayer3", false, true, false))
--mutePlayer(mplayer_custom("Exampleplayer4", false, false, false))
------------------------------------------------------------------------------